services:
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/templates
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/logs:/var/log/nginx
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
      - ./static:/var/www/static
    depends_on:
      - certbot
    networks:
      - nginx_network

  certbot:
    image: certbot/certbot
    container_name: certbot-ssl
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
      - ./nginx/logs:/var/log/letsencrypt
    entrypoint: >
      sh -c "
      trap exit TERM;
      while :; do
        certbot renew --webroot -w /var/www/certbot --quiet;
        nginx -s reload;
        sleep 12h & wait $${!};
      done"
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge

volumes:
  certbot_conf:
  certbot_www:
  nginx_logs:
